### ISSUE TITLE
Could not compile on Ubuntu 20, could not run on MacOS :)

### ISSUE THREAD

**Issue by trurebel** [kirushyk/le#40]
I fetched the project in case it can help me downsize my ML and still keep it portable. I was pleasantly surprise to see it build on MacOS after fetching bits and pieces from "brew", but the latest Ubuntu (tried both gcc9 and gcc10) gave me

`/home/ubuntu/le/bin/../le/tensors/letensor.c:38: undefined reference to `LE_ERROR'
`

On the Mac, I had no luck with the MNIST examples, it might be something trivial but I don't know at this stage

`./mnist-snn 
Segmentation fault: 11`

I also don't know if this is expected behavior

`./polynomial-logistic-regression 
Train set:
x =
[1.000 2.000 3.000 4.000;
 4.000 3.000 2.000 1.000]
y =
[0.000 0.000 1.000 1.000;
 4.000 3.000 2.000 1.000]
Assertion failed: (le_shape_equal(h->shape, y->shape)), function le_logistic_loss, file ../le/leloss.c, line 17.
Iteration 0. Abort trap: 6
`

**Comment by kirushyk** [comment]
Thank you for interest. I will be very happy to assist you.

**Comment by kirushyk** [comment]
The problem with Polynomial Logistic Regression is fixed: labels shape was incorrect.

**Comment by kirushyk** [comment]
Missing inclusion of LE_ERROR is fixed.

**Comment by kirushyk** [comment]
MNIST SNN demo is not ready. At this moment it takes optimizer name (either `bgd` or `sgd` as only command line argument): `./mnist-snn bgd`.

**Comment by kirushyk** [comment]
I fixed multiple Linux and GCC compilation issues.
